POST http://localhost:3000/register/
Content-Type:application/json 

{
    "username":"ramsai24",
    "name":"ramsai", 
    "password":"ramsai123",
    "gender":"male",
    "location":"Pamarru"
}

###

POST http://localhost:3000/login/ 
Content-Type:application/json 

{
    "username":"ramsai24",
    "password":"jnrsai123"
}

###
PUT http://localhost:3000/change-password/ 
Content-Type:application/json 

{
    "username":"ramsai24",
    "oldPassword":"jnrsai123",
    "newPassword":"ramsai123"
}

